### PR TITLE
Adding Mpin zfish neurons dataset integration

### PR DESCRIPTION
**Pull request by FedeClaudi**
@vigji opened the PR here, let's review it before committing?

Building upon `morphapi`'s new `MpinMorphologyAPI` this pull request integrates zfish neurons visualization in `brainrender`. I've added an example to show how to this in `brainrender`. 

The result looks like this:
image

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Among other things, before merging a few things are missing:

- [ ] updated docs with info about this
- [ ] adding some testing for the mpin atlas class + funcs

anything else?

**Comment by vigji** [comment]
It looks like now both ABA and mpin atlas class have a method that basically copy paste a utility function - I guess it would be more convenient to implement that in the generic `Atlas` class right?

**Comment by vigji** [comment]
Looking at the example I have to say it feels a bit strange to have a separate object from a different library for dealing with querying the neurons. I believe we should either have morphapi stuff inside brainrender (inconvenient if we see usage cases outside it) or have it somehow wrapped by some BR layer, maybe inside the Atlas or the Scene

**Comment by FedeClaudi** [comment]
> It looks like now both ABA and mpin atlas class have a method that basically copy paste a utility function - I guess it would be more convenient to implement that in the generic Atlas class right?

This makes sense, if we leave the morphapi stuff separate. Then users can use morphapi to download any neuron they want and a generic atlas `get_neurons` method can support adding them to the scene. 

If, on the other hand, we integrate `morphapi` more into `brainrender`, then `ABA` and `Mpin` will need separate methods as they will be using different `API` classes from `morphapi`.  I'd prefer not to integrate things more because:


* Morphapi offers functionality to **select** which neurons to download given some metadata, which doesn't make much sense to integrate in `brainrender`'s `Atlas` or `Scene` classes
* users might have neurons morphology they already downloaded in some other way and they might want to just render them in `brainrender`, thus the `get_neurons` method should be able to accept `.swc` files or `vedo` actors, don't you think?

Let me know what you think :)

**Comment by vigji** [comment]
> If, on the other hand, we integrate morphapi more into brainrender, then ABA and Mpin will need separate methods as they will be using different API classes from morphapi.
But don't you think that ideally the `morphapi` API should work always in the same way, just passing a different database as the backend, in the way everything is queried from the outside? In that case, there could be a single general method supporting `morphapi` querying. 

> users might have neurons morphology they already downloaded in some other way and they might want to just render them in brainrender, thus the get_neurons method should be able to accept .swc files or vedo actors, don't you think?

I fully agree on this, in any case there should be a method to add neurons directly from file or actor.

**Comment by FedeClaudi** [comment]
okay, so I think I will just move the `get_neurons` method to the main atlas class since it's now used across multiple atlases.

**Comment by FedeClaudi** [comment]
I'll close this PR now. I've put `get_neurons` into the main `Atlas` class so the `Mpin` class is not necessary anymore.

**Pull request closed without merging**
