### PR TITLE
Refactoring suggestions

### PR DESCRIPTION
**Pull request by vigji**
I have been reviewing a bit the code, starting by going through the sections I would be more familiar with (`Atlas`, `Scene`, `utils` around).
In this PR, there are some refactoring suggestions; some of them have been done in one place but if you would go for this concept there might be multiple places I left untouched where such simplifications might help.

In general, before a solid final release the package would benefit from a thorough cleanup, as it looks that different parts of the code are at very different stages, and some classes/methods got a bit overgrown and spread around (random example, web-query related functions in `webqueries` & `data_io`), but I guess it's just that the process is still ongoing.

Still, there are some little redundancies/suboptimalities that makes it a bit hard to dig deeper in the code if someone wants to understand more the code behind the exposed methods, I hope you don't mind if I make the following unrequested comments :) 

Some concrete points that I have seen around and you might want to consider refactoring:
 - Removing multiple implementations of functions to do the same operations on different axes (refactor draft in PR); and using tuple of coordinates instead of separate `z, x, y `makes code more compact in many places;
 - Related to this, I think it would be important to know how generic you want to be about the space/coordinates, ie if you'll always assume bg (allen) orientation for all atlases; in any way you choose this, make it clear somewhere what would "x,y,z" mean for the coordinates (how they interact with specifications such as "rostrocaudal", as some functions (eg `mirror_actor_at_point` use them for axes); this might look too different than usual to users, but one could completely drop "x, y, z" for something more explicit as in bgsace;
 - The `Scene` class is quite heavy and spans from dealing with fitting an electrode position to capturing screenshoots; I think something could be refactor out as it might be useful elsewhere; a lot can be just shortened with neutral refactoring, just writing less verbose code;
- Is actors a collection of dictionaries and lists? that sounds a bit confusing to me;
 - General styling/refactoring tips:
	* in several places there are convoluted nested loops and multiple conditionals, eg with multiple calls to the same functions inside (little example, `mirror_actor_at_point`, with lot of redundant elif that could be dropped with a dict of indexes; or the multiple little sub-functions of `edit_actor`); in many places they could be simplified/rewritten using dict (and kwargs dictionaries to update and pass to the function) to make the flow more intuitive and the code more compact;
	* popping default parameters from a kwargs dictionary is a bit bizarre to follow and I believe entirely equivalent to specify those arguments as kw arguments with their default in the method definition;
	* You make very thorough testing of argument type in many places; 2 notes on this, as in many cases almost doubles the length of your code:
		1) in several places this is redundant as it does not really come from the necessity of supporting multiple types; there simply leaving the statements inside the function would not change that much for the user, and would make the code much more streamlined to follow;
		2) supporting multiple types might good but sometimes you go to very long ends for this; do you make use of all these inconsistent types or you just want it to be very flexible for the user? In the latter case, in most cases it is better to support in a clear way one type only, and let the user understand clearly your code and adapt their inputs to it (first example that comes to attention re-looking at it: mirror_actor_at_point are basically 2 separate functions for 2 separate types of inputs, which you should avoid and if you really need it just have 2 different functions);
	* there's several generic excepts around and
	* inconsistent os + Path usage, but I guess that is also ongoing refactoring

Those are all semi-minor things, but they do impact significantly the possibility of reading code and more importantly make it more bug-prone and harder to maintain. I would be happy to have another look at a further point!

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Hey Luigi, 

Thank you for the thorough review. 

>In general, before a solid final release the package would benefit from a thorough cleanup

I agree, but I tend to get a bit lazy with this and don't always know what's best practice (I tend to repeat what worked before) so it's great to have your comments here. Though part of the messy overly complicated code is just the result of the natural evolution of the package, as you say. Nonetheless, I agree that streamlining the whole code base before release would help both with maintaining it and in letting people read it more clearly.   

I think I agree with all/most of the changes and suggestions you've made, so I will merge this in a branch to go over it in more details. Where you've picked on repeated sub optimal code patterns I will try to fix them everywhere. 


---
> supporting multiple types might good but sometimes you go to very long ends for this; do you make use of all these inconsistent types or you just want it to be very flexible for the user?

The idea was to try and **not** impose restrictions on exactly what kind of argument you can use, but I do agree that it might end up making things worse rather than simpler in some situations. I will try to fix. 

----

One question. When you say: 
> You make very thorough testing of argument type in many places;

what's a better alternative? I'd like to catch gracefully users passing arguments of the wrong kind, but I do agree that it adds a lot of boilerplate code. Any idea?


Thanks again, I'll get to work implementing your advice :)

**Comment by FedeClaudi** [comment]
another comment. 

Self actors is a dictionary which aims to contain a reference to all rendered actors, organized by category. For some categories, e.g. brain regions, it's convenient to have a dictionary with each region's actor, for others like neurons or streamlines this is more complicated so a list is used instead. 

I'll see if I can find a better solution, but if you have suggestions let me know!

**Comment by vigji** [comment]
> what's a better alternative? I'd like to catch gracefully users passing arguments of the wrong kind, but I do agree that it adds a lot of boilerplate code. Any idea?

The first one is to separate mentally (or even in code, with the _ prefix) the methods that you want to keep internal and the ones that you want to expose to the user. In the first type, you basically never have to do that, and I believe python discourage you from doing so. Even in the second scenario, the best way in most cases is to just be careful specifying desired types in the docstrings and give users the responsibility of fixing it and passing the right one if they are using something wrongly. The only exception would be something that is so potentially ambiguous that even you the author don't remember what's the required type sometimes - in that case, you probably want a graceful fail, or fixing the type yourself (eg: `add_actor_label`, [although is probably internal - in which case would be also nice to call it `_add_actor_label`] , I think is so obvious in the required types actor and string that I would not control for it;  on the other hand, it might be ambiguous in its use of single values or lists, so I would totally leave your initial type fix)

**Comment by vigji** [comment]
> Self actors is a dictionary which aims to contain a reference to all rendered actors, organized by category. For some categories, e.g. brain regions, it's convenient to have a dictionary with each region's actor, for others like neurons or streamlines this is more complicated so a list is used instead.

Sorry, I misunderstood this - I think this way makes total sense!

**Comment by vigji** [comment]
Another minor thing I noticed in the `load_cells_from_file` function: supported_formats includes the .csv but in line 61 you check if something is in this for opening it with h5 (as csv case is handled before); works but it is a bit confusing.

But also in this case as it is a further example: users can have potentially veri different custom file formats for cells, so I would not exposed to them something like `add_cells_from_file`; for them is one line more to read their datatype correctly before passing it as data frame or numpy array; for you is 100 lines to deal with different scenarios, and potentially still risking to disappoint them if their format fail. I think you aim at spoiling them 100%, but that can become counterproductive at times :)

**Comment by vigji** [comment]
Also, in terms of general structure, I am a bit unconvinced by a `Scene` class that handles both something extremely close to data, and data specificities like fitting a probe or defining a cannula (either bizarre in species other than the mouse) and something very close to the graphical side of the implementation like the rendering. I would aim at moving all "methods supporting scene population" in the relative brainrender atlas classes, and leave here only very generic stuff like hairline.

Thinking more about this, I see where this organisation was coming from, but if you want to support multiple species/situations, a `Scene` class exposed with an `Atlas` "backend" will always be funny, as the Atlas is what is characterising what the user is doing (eg, working with fish points or mouse/rat cannule or c elegant connectomics). To go that direction I believe it would make much more sense to have an Atlas (or differently named, but what is currently atlas) exposed to the user, with add cannule, reconstructed neurons and whatnot, which will be using the `Scene` "backend" to render actors once it creates them in its methods

**Comment by FedeClaudi** [comment]
Thanks. 

I'm not sure I get what the proposed solution for `add_cells_from_file`?

I see your point about inverting the logic between `scene` and `atlas`, but I'm not sure it would make to much of a difference. Ans it would be a lot of work to change everything including docs etc. I will try to streamline the scene class instead so that it's confined to visualizing data computed elsewhere.

**Comment by FedeClaudi** [comment]
Hey I've started making some improvements in the `refactor` branch:
* I've removed utility functions that were not used anymore + re-organized some of the ones left
* I've shortened `Scene` by one third, though most of it was just by moving code to functions defined elsewhere. So the total number of LOC hasn't changed much, but hopefully it helps with readability. 
* I've transitioned from `os` to `pathlib` in most places though not everywhere
* I've turned `scene.actors` into a simple list 

The thing I haven't done yet is dealing with those functions that can accept a lot of different types of arguments. 

If you have time to have a look, let me know if you find that things improved and how you'd make it even better

**Comment by vigji** [comment]
It is definitively getting cleaner!

> I'm not sure I get what the proposed solution for add_cells_from_file?
What I was suggesting was just dropping support for the file entirely and have users loading the file (should be a one-liner for them) and passing it to `add_cells`. I know it is drastic, as you have this you might just keep it, it's just the general philosophy of focusing on the moving parts you are helping people dealing with: if you go this way you can have users legitimately complaining about their file not loading here, even though the problem might be in whatever hdf5 I/O library they are using.

> I see your point about inverting the logic between scene and atlas, but I'm not sure it would make to much of a difference. Ans it would be a lot of work to change everything including docs etc. I will try to streamline the scene class instead so that it's confined to visualizing data computed elsewhere.

I have seen the refactoring of code out of the class. I still think that having here attributes for such a spectrum of features (data to rendering/cameras etc) is difficult to get from the outside. A proposal for a usage- and docs-neutral refactoring: maybe you can keep the concept of `Scene` as it is used now, but offload the graphics part (rendering, cameras, taking screenshots, export) to a `SceneRender` class (or whatever other name), where users can easily find everything strictly related to the rendering part. At this point, the only thing that you would need to share is the list/dict of `actors`, right? Then scene can just have a `SceneRender` object set as method, which is invoked if required. This would definitively move it in the right direction, although it would not deal with the problem of atlas-species-specific methods.

Other general comment:  with `bg-atlasapi` now the `Atlas` class is practically a leftover no? as it is so empty now everything could be moved (back?) to the Base one (`_planes_norms` are health with in the `_space` now)

**Comment by FedeClaudi** [comment]
Very good points. 

I've created a `Render` class which takes care of creating the `Plotter`, renderings, screenshots etc. 
Now `Scene` is just for adding elements to the scene with the necessary operations that this entails in some cases. 
`Scene` inherits `Render` so from the user's perspective nothing changes. 

I've also removed `atlases.base` and just have it all under `Atlas`. I should check at some point how much of `Atlas`'s code is redundant with brainglobe...

**Pull request merged**
